language: node_js
node_js:
  - "stable"

services:
  - docker

cache:
  directories:
    - node_modules

before_install:
  - npm install -g truffle
  - docker run -d -p 8545:8545 trufflesuite/ganache-cli:latest

script:
  - truffle migrate
  - truffle test
